-- 1. Tabel Guests
CREATE TABLE IF NOT EXISTS guests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roomNo1 TEXT,
  roomNo2 TEXT,
  jumlahTamu INTEGER,
  jumlahKamar INTEGER,
  jenisKamar TEXT,
  receptionist TEXT,
  nama TEXT,
  pekerjaan TEXT,
  perusahaan TEXT,
  kebangsaan TEXT,
  noKtp TEXT,
  tanggalLahir TEXT,
  alamat TEXT,
  telepon TEXT,
  email TEXT,
  waktuKedatangan TEXT,
  tanggalKedatangan TEXT,
  tanggalKeberangkatan TEXT,
  noMember TEXT,
  safetyDepositBox TEXT,
  dikeluarkanOleh TEXT,
  tanggal TEXT,
  metodePembayaran TEXT,
  cardNumber TEXT,
  cardHolderName TEXT,
  cardType TEXT,
  expiredDate TEXT,
  bankTransferTo TEXT,
  mandiriAccount TEXT,
  mandiriNameAccount TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Users (untuk Login)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'staff'
);

-- 3. Tambahkan user admin default
-- Jalankan ini hanya jika tabel users masih kosong
INSERT INTO users (username, password, role)
SELECT 'admin', 'admin123', 'admin'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin');
